#!/usr/bin/env bash
set -e

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

payload=$(mktemp /tmp/resource-in.XXXXXX)

cat > $payload <&0

echo "Nothing todo here"

jq -n '{
  version: {
    ref: "none"
  }
}' >&3

