#!/usr/bin/env bash
set -e

exec 3>&1
exec 1>&2

destination=$1

if [ -z "$destination" ]; then
  echo "usage: $0 <path/to/destination>" >&2
  exit 1
fi

payload=$(mktemp /tmp/resource-in.XXXXXX)

cat > $payload <&0

jq -n '{
  version: {
    ref: "none"
  }
}' >&3

